// palavras.js
const palavras = [
    // === OBJETOS E CASA ===
    "ABAJUR", "ARMÁRIO", "ASPIRADOR", "BALDE", "BANHEIRA", "BERÇO", 
    "BORRACHA", "CADEADO", "CADEIRA", "CADERNO", "CAIXA", "CAMA", 
    "CANETA", "CARTEIRA", "CHAVE", "COBERTOR", "COLCHÃO", "COLHER", 
    "COMPUTADOR", "COPO", "CORTINA", "ESPELHO", "ESTOJO", "FACA", 
    "FECHADURA", "FOGÃO", "FRIGIDEIRA", "GAVETA", "GELADEIRA", "GUARDA-CHUVA", 
    "INTERRUPTOR", "LÂMPADA", "LÁPIS", "LIQUIDIFICADOR", "LIXEIRA", "MALA", 
    "MARTELO", "MESA", "MICRO-ONDAS", "MOCHILA", "NOTEBOOK", "PANELA", 
    "PARAFUSO", "PINCEL", "PORTA", "PRATELEIRA", "PRATO", "QUADRO", 
    "RÁDIO", "RELÓGIO", "RODO", "SABONETE", "SOFÁ", "TALHER", 
    "TAPETE", "TELEFONE", "TELEVISÃO", "TESOURA", "TOALHA", "TORNEIRA", 
    "TRAVESSEIRO", "VASO", "VASSOURA", "VENTILADOR", "XÍCARA",

    // === ANIMAIS ===
    "ABELHA", "ÁGUIA", "ARANHA", "ARARA", "AVESTRUZ", "BALEIA", 
    "BARATA", "BESOURO", "BORBOLETA", "CACHORRO", "CAMELO", "CANGURU", 
    "CARANGUEJO", "CAVALO", "CISNE", "COBRA", "COELHO", "CORUJA", 
    "CROCODILO", "DINOSSAURO", "DRAGÃO", "ELEFANTE", "ESCORPIÃO", "ESQUILO", 
    "FALCÃO", "FORMIGA", "GALINHA", "GATO", "GIRAFA", "GOLFINHO", 
    "GORILA", "HIPOPÓTAMO", "JACARÉ", "JOANINHA", "LEÃO", "LOBO", 
    "MACACO", "MARIPOSA", "MINHOCA", "MORCEGO", "MOSCA", "MOSQUITO", 
    "OVELHA", "PANTERA", "PATO", "PAVÃO", "PEIXE", "PINGUIM", 
    "POLVO", "PORCO", "RAPOSA", "RATO", "RINOCERONTE", "SAPO", 
    "TARTARUGA", "TIGRE", "TOURO", "TUBARÃO", "URSO", "VEADO", "ZEBRA",

    // === ALIMENTOS E BEBIDAS ===
    "ABACATE", "ABACAXI", "AÇÚCAR", "ALFACE", "ALHO", "AMENDOIM", 
    "ARROZ", "AZEITE", "BACON", "BATATA", "BERINJELA", "BETERRABA", 
    "BISCOITO", "BOLO", "BRÓCOLIS", "CACHORRO-QUENTE", "CAFÉ", "CARNE", 
    "CEBOLA", "CENOURA", "CEREJA", "CERVEJA", "CHÁ", "CHOCOLATE", 
    "CHURRASCO", "COCO", "COGUMELO", "COXINHA", "DOCE", "ESFIHA", 
    "FARINHA", "FEIJÃO", "FRANGO", "HAMBÚRGUER", "IOGURTE", "LARANJA", 
    "LEITE", "LIMÃO", "LINGUIÇA", "MAÇÃ", "MACARRÃO", "MAMÃO", 
    "MANTEIGA", "MARACUJÁ", "MELANCIA", "MILHO", "MORANGO", "OVO", 
    "PÃO", "PASTEL", "PEIXE", "PIMENTA", "PIPOCA", "PIZZA", 
    "PRESUNTO", "QUEIJO", "REFRIGERANTE", "SAL", "SALADA", "SALGADO", 
    "SALSICHA", "SANDUÍCHE", "SOPA", "SORVETE", "SUCO", "TOMATE", "UVA",

    // === PROFISSÕES ===
    "ADVOGADO", "ASTRONAUTA", "ATOR", "BOMBEIRO", "CANTOR", "CARPINTEIRO", 
    "CIENTISTA", "COSTUREIRA", "COZINHEIRO", "DENTISTA", "DIRETOR", "ELETRICISTA", 
    "ENCANADOR", "ENFERMEIRO", "ENGENHEIRO", "ESCRITOR", "FOTÓGRAFO", "GARÇOM", 
    "JOGADOR", "JORNALISTA", "JUIZ", "MECÂNICO", "MÉDICO", "MOTORISTA", 
    "PADEIRO", "PINTOR", "POLICIAL", "PREFEITO", "PROFESSOR", "VENDEDOR", 
    "VETERINÁRIO",

    // === CORPO HUMANO E VESTUÁRIO ===
    "ANEL", "BARBA", "BARRIGA", "BERMUDA", "BIGODE", "BLUSA", 
    "BOCA", "BONE", "BOTA", "BRAÇO", "BRINCO", "CABEÇA", 
    "CABELO", "CACHECOL", "CALÇA", "CAMISA", "CASACO", "CÉREBRO", 
    "CHAPÉU", "CINTO", "COLAR", "CORAÇÃO", "CORPO", "COTOVELO", 
    "DEDO", "DENTE", "ESTÔMAGO", "GRAVATA", "JAQUETA", "JOELHO", 
    "LÁBIO", "LÍNGUA", "LUVA", "MÃO", "MEIA", "MOLETOM", 
    "NARIZ", "ÓCULOS", "OLHO", "OMBRO", "ORELHA", "OSSO", 
    "PÉ", "PELE", "PERNA", "PESCOÇO", "PULSEIRA", "PULMÃO", 
    "SAIA", "SANDÁLIA", "SAPATO", "SANGUE", "SOBRANCELHA", "TÊNIS", 
    "UNHA", "VESTIDO",

    // === LUGARES E NATUREZA ===
    "AEROPORTO", "APARTAMENTO", "ÁRVORE", "AVENIDA", "BANCO", "BIBLIOTECA", 
    "CACHOEIRA", "CASTELO", "CAVERNA", "CÉU", "CHUVAS", "CIDADE", 
    "CINEMA", "CLÍNICA", "DESERTO", "ESCOLA", "ESTÁDIO", "ESTRELA", 
    "FARMÁCIA", "FLORESTA", "FOGO", "FURACÃO", "GALÁXIA", "GELO", 
    "HOSPITAL", "IGREJA", "ILHA", "LAGO", "LUA", "MAR", 
    "MERCADO", "MONTANHA", "MUSEU", "NEVE", "NUVEM", "OCEANO", 
    "PADARIA", "PAÍS", "PARQUE", "PEDRA", "PLANETA", "PONTE", 
    "PORTÃO", "PRAÇA", "PRAIA", "PRÉDIO", "RESTAURANTE", "RIO", 
    "RUA", "SHOPPING", "SOL", "TEATRO", "TEMPESTADE", "TERRA", 
    "TERREMOTO", "UNIVERSO", "VULCÃO",

    // === VEÍCULOS E TRANSPORTES ===
    "AMBULÂNCIA", "AVIÃO", "BALÃO", "BARCO", "BICICLETA", "BOMBEIRO", 
    "CAMINHÃO", "CARRO", "CARROÇA", "FOGUETE", "HELICÓPTERO", "LANCHA", 
    "METRÔ", "MOTO", "NAVIO", "ÔNIBUS", "PATINETE", "PATINS", 
    "SKATE", "SUBMARINO", "TRATOR", "TREM",

    // === AÇÕES, SENTIMENTOS E CONCEITOS ===
    "ABRAÇO", "ALEGRIA", "AMIZADE", "AMOR", "BELEZA", "BRINCADEIRA", 
    "CARINHO", "CIÚME", "CORAGEM", "CORRIDA", "DANÇA", "ESPERANÇA", 
    "FESTA", "FOME", "FORÇA", "FRIO", "GUERRA", "INVERNO", 
    "LEITURA", "MAGIA", "MEDO", "MENTIRA", "MISTERIO", "MÚSICA", 
    "NATUREZA", "OUTONO", "PAIXÃO", "PAZ", "PESADELO", "PINTURA", 
    "PRIMAVERA", "RAIVA", "SAUDADE", "SEGREDO", "SILÊNCIO", "SONHO", 
    "SORRISO", "SORTE", "SUCESSO", "SUSTO", "TRABALHO", "TRISTEZA", 
    "VELOCIDADE", "VERÃO", "VERDADE", "VIAGEM", "VITÓRIA",

    // === INSTRUMENTOS MUSICAIS E ARTE ===
    "ACORDEÃO", "BAIXO", "BATERIA", "CINEMA", "CLARINETE", "DESENHO", 
    "FLAUTA", "FOTOGRAFIA", "GAITA", "GUITARRA", "HARPA", "MICROFONE", 
    "PALCO", "PANDEIRO", "PIANO", "POESIA", "SAXOFONE", "TAMBOR", 
    "TECLADO", "TROMBONE", "TROMPETE", "VIOLÃO", "VIOLINO",

    // === ESPORTES E HOBBIES ===
    "ATLETISMO", "BASQUETE", "BOLICHE", "BOXE", "CAPOEIRA", "CICLISMO", 
    "DAMA", "ESGRIMA", "GINÁSTICA", "GOLFE", "JUDÔ", "KARATÊ", 
    "NATAÇÃO", "PATINAÇÃO", "PESCARIA", "PINGUE-PONGUE", "RUGBY", "SURFE", 
    "TÊNIS", "VÔLEI", "XADREZ", "YOGA",

    // === FERRAMENTAS E CONSTRUÇÃO ===
    "ALICATE", "AREIA", "BETONEIRA", "BRITA", "CAPACETE", "CIMENTO", 
    "ENXADA", "ESCADA", "ESQUADRO", "FURADEIRA", "GESSO", "MARRETA", 
    "PÁ", "PREGO", "ROLO", "SERROTE", "TIJOLO", "TINTA",

    // === NATUREZA E GEOGRAFIA ===
    "ARGILA", "ARQUIPÉLAGO", "BAÍA", "BRONZE", "CONTINENTE", "CRISTAL", 
    "DIAMANTE", "FÓSSIL", "FUMAÇA", "GEADA", "GRANIZO", "LAMA", 
    "NEBLINA", "ORVALHO", "OURO", "PENÍNSULA", "PLANALTO", "PLANÍCIE", 
    "POÇO", "PRATA", "ROCHA", "VALE",

    // === HIGIENE E BELEZA ===
    "BATOM", "CONDICIONADOR", "COTONETE", "CURATIVO", "DESODORANTE", 
    "ESMALTE", "FRALDA", "LIXA", "MAQUIAGEM", "PERFUME", "PINÇA", 
    "POMADA", "SABONETE", "SHAMPOO",

    // === ESCRITÓRIO E ESCOLA ===
    "APONTADOR", "ARQUIVO", "BORRACHA", "CARIMBO", "CARTOLINA", "CLIPE", 
    "COMPASSO", "DUREX", "ENVELOPE", "GIZ", "GRAMPEADOR", "LOUSA", 
    "MARCADOR", "PASTA", "RÉGUA",

    // === VESTUÁRIO ESPECÍFICO ===
    "BIQUÍNI", "BOTÃO", "CALCINHA", "COLETE", "CUECA", "FIVELA", 
    "GORRO", "MAIÔ", "PIJAMA", "ROUPÃO", "SUNGA", "SUSPENSÓRIO", 
    "SUTIÃ", "ZÍPER",

    // === TECNOLOGIA E CIÊNCIAS ===
    "ANTENA", "APLICATIVO", "ÁTOMO", "ÁUDIO", "BACTÉRIA", "BATERIA", 
    "CABO", "CÉLULA", "DRONE", "ENERGIA", "GRAVIDADE", "ÍMÃ", 
    "LENTE", "MICROCHIP", "MICROSCÓPIO", "RADAR", "ROBÔ", "SATÉLITE", 
    "SENHA", "TELESCOPIO", "TOMADA", "VÍDEO", "VÍRUS",

    // === FESTAS, EVENTOS E DATAS ===
    "ANIVERSÁRIO", "BALÃO", "BATIZADO", "CARNAVAL", "CASAMENTO", 
    "CONFETE", "FANTASIA", "FORMATURA", "MÁSCARA", "NATAL", 
    "PÁSCOA", "RÉVEILLON", "SERPENTINA", "VELA",

    // === MITOLOGIA E FANTASIA ===
    "AMULETO", "BRUXA", "CENTAURO", "DUENDE", "FADA", "FEITIÇO", 
    "GÊNIO", "GIGANTE", "LOBISOMEM", "MAGO", "MONSTRO", "POÇÃO", 
    "SEREIA", "UNICÓRNIO", "VAMPIRO", "ZUMBI",

    // === CORES E FORMAS ===
    "AMARELO", "AZUL", "BRANCO", "CINZA", "CÍRCULO", "CUBO", 
    "ESFERA", "LARANJA", "MARROM", "PIRÂMIDE", "PRETO", "QUADRADO", 
    "RETÂNGULO", "ROSA", "ROXO", "TRIÂNGULO", "VERDE", "VERMELHO",

    // === VERBOS E AÇÕES NO INFINITIVO ===
    "ANDAR", "BEBER", "CANTAR", "CHORAR", "COMER", "CORRER", 
    "DORMIR", "ESTUDAR", "FALAR", "GRITAR", "JOGAR", "NADAR", 
    "PENSAR", "PULAR", "RIR", "VOAR",

    // === PARTES DE VEÍCULOS E TRÂNSITO ===
    "ACELERADOR", "ASFALTO", "BUZINA", "CAPÔ", "CATRACA", "EMBREAGEM", 
    "ESTEPE", "FAROL", "FREIO", "GARAGEM", "MARCHA", "MOTOR", 
    "PEDAL", "PNEU", "PORTA-MALAS", "RETROVISOR", "RODOVIA", "SEMÁFORO", 
    "TRÂNSITO", "VOLANTE",

    // === UTENSÍLIOS DE COZINHA E CASA ===
    "ASSADEIRA", "CANECA", "CHALEIRA", "COADOR", "CONCHA", "ESCORREDOR", 
    "ESCUMADEIRA", "ESPATULA", "FORMA", "FRUTEIRA", "FUNIL", "GARRAFA", 
    "JARRA", "LIXA", "RALADOR", "RALO", "ROLHA", "TAÇA", 
    "TÁBUA", "TIGELA", "VARAL", "VÍSOURA",

    // === ESPAÇO, TEMPO E CLIMA ===
    "AMANHÃ", "ANO", "COMETA", "DÉCADA", "ECLIPSE", "ESTAÇÃO", 
    "FUTURO", "HORA", "METEORO", "MILÊNIO", "MINUTO", "ONTEM", 
    "ÓRBITA", "PASSADO", "PRESENTE", "SÉCULO", "SEMANA", "TARDE", 
    "TROVÃO", "VENDAVAL",

    // === CASA, JARDIM E CONSTRUÇÃO ===
    "ALARME", "ANDAR", "ANTENA", "CALÇADA", "CERCA", "CHAMINÉ", 
    "DEGRAU", "ELEVADOR", "FACHADA", "GRAMA", "JARDIM", "MURO", 
    "PÁTIO", "QUINTAL", "RODAPÉ", "SACADA", "SÓTÃO", "TELHA", 
    "TELHADO", "TÉRREO", "VARANDA",

    // === CORPO, SAÚDE E SINTOMAS ===
    "ALERGIA", "CICATRIZ", "FEBRE", "GIPE", "INJEÇÃO", "LÁGRIMA", 
    "MÚSCULO", "NERVO", "RAIO-X", "RECEITA", "REMÉDIO", "RESPIRAÇÃO", 
    "SALIVA", "SUOR", "TOSSE", "VACINA", "VEIA", "VISÃO",

    // === PROFISSÕES EXTRAS E CARGOS ===
    "ARQUITETO", "ASSISTENTE", "CAIXA", "CHEFE", "DETETIVE", "FAXINEIRO", 
    "FERREIRO", "GERENTE", "INSPETOR", "JARDINEIRO", "MAQUINISTA", "MARINHEIRO", 
    "OURIVES", "PILOTO", "PORTEIRO", "RECEPCIONISTA", "SÍNDICO", "ZELADOR",

    // === MUNDO GEEK E ENTRETENIMENTO ===
    "ANIME", "CÂMERA", "CANAL", "CONTROLE", "COSPLAY", "DESAFIO", 
    "GAMES", "HERÓI", "INGRESSO", "MANGÁ", "NOVELA", "PIXEL", 
    "QUADRINHOS", "SÉRIE", "TELA", "VIDEOGAME", "VILÃO",

    // === AVENTURA E MISTÉRIO ===
    "ÂNCORA", "ARMADILHA", "BARRACA", "BÚMERANGUE", "BÚSSOLA", "CABANA", 
    "CAÇADOR", "CORDA", "ENIGMA", "FOGUEIRA", "LABIRINTO", "LUNETA", 
    "MAPA", "PIRATA", "TESOURO", "TRILHA",

    // === MÚSICA E DANÇA ===
    "BALÉ", "BANDA", "CORAL", "DISCO", "FORRÓ", "LETRA", 
    "MELODIA", "PAGODE", "RITMO", "SAMBA", "TANGO", "VALSA",

    // === ACESSÓRIOS E DETALHES DE ROUPA ===
    "BOLSA", "CAPA", "CARTEIRA", "COROA", "CRACHÁ", "DIADEMA", 
    "GOLA", "MANGA", "MOCHILA", "RENDAS", "TÚNICA", "VÉU",

    // === ALIMENTOS E TEMPEROS EXTRAS ===
    "AMORA", "AMÊNDOA", "AVELÃ", "BACALHAU", "CAMARÃO", "CANELA", 
    "CARAMELO", "CASTANHA", "CHANTILLY", "CHICLETE", "COENTRO", "COUVE", 
    "CRAVO", "EMPADA", "ESPINAFRE", "FRAMBOESA", "GOIABA", "HORTELÃ", 
    "JACA", "KIWI", "LENTILHA", "MAIONESE", "MANJERICÃO", "MELÃO", 
    "MOSTARDA", "NOZ", "OSTRA", "PANQUECA", "PÊSSEGO", "PICLES", 
    "QUIABO", "REPOLHO", "RÚCULA", "SALMÃO", "SALSA", "SUSPIRO", 
    "TAPIOCA", "TORRADA", "TRUFA", "VINAGRE",

    // === ANIMAIS EXTRAS ===
    "AVESTRUZ", "CAMALEÃO", "CASTOR", "CISNE", "DONINHA", "FOCA", 
    "GUAXINIM", "HIENA", "IGUANA", "JAVALI", "LHAMA", "MORSA", 
    "PANTERA", "PREGUIÇA", "PUMA", "RENA", "SAPO", "TEXUGO", 
    "TOUPEIRA", "URUBU",

    // === PROFISSÕES, TÍTULOS E TIPOS HUMANOS ===
    "ACROBATA", "ALFAIATE", "ARTESÃO", "ASTRÔNOMO", "BABÁ", "BARÃO", 
    "BARBEIRO", "BIÓLOGO", "BISPO", "CACIQUE", "CAMPEÃO", "CAPITÃO", 
    "CARTEIRO", "COBRADOR", "CONDE", "COVEIRO", "DIPLOMATA", "DUQUE", 
    "ESPIÃO", "FERREIRO", "FILÓSOFO", "FISCAL", "FRADE", "GARIMPEIRO", 
    "GÊNIO", "GUARDIÃO", "HERDEIRO", "IMPERADOR", "LIXEIRO", "MÁGICO", 
    "MONGE", "OPERÁRIO", "PADEIRO", "PAJÉ", "PEDREIRO", "POETA", 
    "REI", "SAPATEIRO", "SOLDADO", "SURFISTA", "TENENTE", "TRADUTOR",

    // === OBJETOS E COISAS DIVERSAS ===
    "ALMOFADA", "CABIDE", "CANTIL", "CHIBATA", "CHUPETA", "CINTO", 
    "CLIPE", "DEDAL", "ESPANADOR", "ESTRIBO", "FITA", "FRASCO", 
    "GATILHO", "GAIOLA", "GANCHO", "HASTE", "ISQUEIRO", "JARRO", 
    "LENÇOL", "LONA", "MACA", "NARGUILÉ", "NOVELO", "PALITO", 
    "PANO", "PEDAL", "PENICO", "PINÇA", "PIRES", "POMADA", 
    "PREGO", "REGADOR", "RODO", "ROLO", "SIFÃO", "SUPORTE", 
    "TAMPA", "TERMÔMETRO", "TRINCO", "VASO", "XALE",

    // === NATUREZA, CIÊNCIA E GEOGRAFIA ===
    "ABISMO", "ALICERCE", "ALTITUDE", "AMIANTO", "AMÔNIA", "ASTEROIDE", 
    "AURORA", "BREJO", "CACTO", "CALCÁRIO", "CARBONO", "CASCATA", 
    "CAULE", "CAVERNA", "CICLONE", "CIPÓ", "COBRE", "COLINA", 
    "COMETA", "CRATERA", "CRISTAL", "DELTA", "DUNA", "ECLIPSE", 
    "ENCOSTA", "ENXOFRE", "EQUADOR", "EROSÃO", "FALÉSIA", "FOZ", 
    "FRONDOSO", "GALHO", "GEADA", "GELEIRA", "GRANITO", "GRAVIDADE", 
    "HORIZONTE", "ICEBERG", "ÍMÃ", "ISÓTOPO", "JAZIDA", "LAGOA", 
    "LAVA", "LÍQUEN", "MAGMA", "MANGUE", "MARÉ", "METEORO", 
    "MUSGO", "NASCENTE", "NEBLINA", "NÊUTRON", "NÚCLEO", "OÁSIS", 
    "ORVALHO", "OZÔNIO", "PÂNTANO", "PLANÍCIE", "PLASMA", "POÇO", 
    "PÓLEN", "POMAR", "PRÓTON", "RADIAÇÃO", "RAIZ", "RAVINA", 
    "RECIFE", "RELÂMPAGO", "RELEVO", "RESINA", "RIACHO", "SAVANA", 
    "SEMENTE", "SILÍCIO", "TEMPESTADE", "TERREMOTO", "TRONCO", "TSUNAMI", 
    "TUFÃO", "URÂNIO", "VALE", "VAPOR", "VENDAVAL", "VULCÃO"
];

module.exports = palavras;